# Generated by Django 6.0.6 on 2026-08-03 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('OSM', 'OpenStreetMap'), ('LGU', 'Local Government Unit'), ('PSA', 'Philippine Statistics Authority')], max_length=20)),
                ('signal_type', models.CharField(choices=[('CCTV', 'CCTV Camera'), ('LIGHT', 'Street Light'), ('POLICE', 'Police Station'), ('MEDICAL', 'Medical Center')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('LIGHTING', 'Lighting Issue'), ('HAZARD', 'Road/Obstuction Hazard'), ('INCIDENT', 'Security Incident'), ('ACCIDENT', 'Traffic Accident')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='APPROVED', max_length=20)),
                ('confidence_score', models.IntegerField(default=1)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
