# Generated by Django 6.0.6 on 2026-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='PENDING', max_length=20),
        ),
    ]
