# Generated by Django 6.0.6 on 2026-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_data', '0002_alter_incidentreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='safetysignal',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='safetysignal',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=9, max_digits=12),
        ),
    ]
