# Generated by Django 6.0.6 on 2026-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_data', '0003_alter_incidentreport_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
    ]
